/*
 * This file is generated by jOOQ.
*/
package lab07.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lab07.jooq.tables.Book;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lab07 extends SchemaImpl {

    private static final long serialVersionUID = -1820764970;

    /**
     * The reference instance of <code>lab07</code>
     */
    public static final Lab07 LAB07 = new Lab07();

    /**
     * The table <code>lab07.book</code>.
     */
    public final Book BOOK = lab07.jooq.tables.Book.BOOK;

    /**
     * No further instances allowed
     */
    private Lab07() {
        super("lab07", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Book.BOOK);
    }
}
