/*
 * This file is generated by jOOQ.
*/
package lab07.jooq;


import javax.annotation.Generated;

import lab07.jooq.tables.Book;


/**
 * Convenience access to all tables in lab07
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>lab07.book</code>.
     */
    public static final Book BOOK = lab07.jooq.tables.Book.BOOK;
}
